version: '3'
services:
  signal-server:
    build:
      context: ./signal-server
      dockerfile: ./cmd/signal-server/Dockerfile
    ports:
      - "3002:3002"
      - "50002:50002"

  client:
    build:
      context: ./client
    ports:
      - "8080:80"
